# Generated by Django 5.2 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_user_name_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
