# Generated by Django 5.2 on 2025-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(max_length=12, null=True, unique=True),
        ),
    ]
