# Generated by Django 5.2 on 2025-04-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_person_health_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="health_status",
        ),
        migrations.DeleteModel(
            name="person",
        ),
    ]
