# Generated by Django 5.2 on 2025-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_delete_health_status_delete_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mykad",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
