# Generated by Django 5.2 on 2025-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_user_mykad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mykad",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
