# Generated by Django 5.2 on 2025-05-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_user_mykad"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_types",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B+"),
                    ("b-", "B-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                ],
                max_length=10,
            ),
        ),
    ]
