# Generated by Django 5.2 on 2025-05-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_user_race"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("malays", "Malays"),
                    ("chinese", "Chinese"),
                    ("indians", "Indians"),
                    ("others", "Others"),
                ],
                max_length=30,
            ),
        ),
    ]
