# Generated by Django 5.2 on 2025-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_user_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="drug_sensitivity",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
