# Generated by Django 5.2 on 2025-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_user_drug_sensitivity_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
