# Generated by Django 5.2 on 2025-05-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_user_is_verified_user_verification_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_code",
        ),
    ]
