# Generated by Django 5.2 on 2025-05-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_remove_user_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="health_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("darkCircle", models.BooleanField()),
                ("lipDry", models.BooleanField()),
                ("stroke", models.BooleanField()),
                ("skinIssue", models.CharField(max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.person"
                    ),
                ),
            ],
        ),
    ]
