# Generated by Django 5.2 on 2025-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_person_health_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="health_status",
            name="person",
        ),
        migrations.AlterField(
            model_name="health_status",
            name="darkCircle",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="health_status",
            name="lipDry",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="health_status",
            name="skinIssue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="health_status",
            name="stroke",
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name="person",
        ),
    ]
