# Generated by Django 5.2 on 2025-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_remove_health_status_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="health_status",
            name="darkCircle",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="health_status",
            name="lipDry",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="health_status",
            name="stroke",
            field=models.BooleanField(default=False),
        ),
    ]
