# Generated by Django 5.2 on 2025-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_alter_health_status_darkcircle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="health_status",
        ),
    ]
