# Generated by Django 5.2 on 2025-05-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_health_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="health_status",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_name",
                to="base.person",
            ),
        ),
    ]
