# Generated by Django 5.2 on 2025-05-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_alter_health_status_person"),
    ]

    operations = [
        migrations.DeleteModel(
            name="health_status",
        ),
    ]
