# Generated by Django 5.2 on 2025-05-27 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_delete_health_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="health_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("darkCircle", models.BooleanField(default=False)),
                ("lipDry", models.BooleanField(default=False)),
                ("stroke", models.BooleanField(default=False)),
                ("skinIssue", models.CharField(max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_name",
                        to="base.person",
                    ),
                ),
            ],
        ),
    ]
