# Generated by Django 5.2 on 2025-05-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_health_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="alertImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="alertImage/")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="health_status",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.alertimage",
            ),
        ),
    ]
