# Generated by Django 5.2 on 2025-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_alertimage_health_status_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertimage",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
