# Generated by Django 5.2 on 2025-06-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_alter_alertimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="safetyStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hat", models.BooleanField(default=False)),
                ("no_hat", models.BooleanField(default=False)),
                ("vest", models.BooleanField(default=False)),
                ("no_vest", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.alertimage",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_name",
                        to="base.person",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="health_status",
        ),
    ]
