# Generated by Django 5.2 on 2025-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_safetystatus_delete_health_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
