# Generated by Django 5.2 on 2025-06-29 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_user_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime(2025, 6, 1, 0, 0)
            ),
            preserve_default=False,
        ),
    ]
