# Generated by Django 5.2 on 2025-07-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_person_created"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmergencyContact",
        ),
    ]
