# Generated by Django 5.2 on 2025-07-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_delete_emergencycontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blood_types",
        ),
        migrations.RemoveField(
            model_name="user",
            name="drug_sensitivity",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mykad",
        ),
        migrations.RemoveField(
            model_name="user",
            name="race",
        ),
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
    ]
