# Generated by Django 5.2.2 on 2025-07-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_remove_user_blood_types_remove_user_drug_sensitivity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="healthStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dark_circles",
                    models.CharField(
                        choices=[
                            ("none", "No Dark Circles"),
                            ("mild", "Mild Dark Circles"),
                            ("moderate", "Moderate Dark Circles"),
                            ("severe", "Severe Dark Circles"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "lip_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal Lips"),
                            ("dry", "Dry Lips"),
                            ("chapped", "Chapped Lips"),
                            ("pale", "Pale Lips"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "skin_condition",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy Skin"),
                            ("acne", "Acne"),
                            ("dry", "Dry Skin"),
                            ("oily", "Oily Skin"),
                            ("sensitive", "Sensitive Skin"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.alertimage",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_name",
                        to="base.person",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="safetyStatus",
        ),
    ]
